name: release
on:
  push:
    # Sequence of patterns matched against tags
    # Right now, we run this job automatically when a semantically versioned
    # tag is pushed (with an optional suffix).
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'
jobs:
  build-and-release:
    name: Build and release gilligan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v3
      - name: Set env ðŸ“‹
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Install ðŸ“¦
        run: |
          yarn install --frozen-lockfile
      - name: Build ðŸš§
        run: |
          yarn build
        env:
          CI: false
      - name: Unit tests ðŸ”§
        run: |
          yarn test
      - name: Package ðŸ“¦
        run: |
          cd build/ && tar -zcvf ../console-${RELEASE_VERSION}.tgz --exclude='./data' .
      - name: Create Draft Release
        id:  create_release
        uses: actions/create-release@v1
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
           tag_name: ${{ github.ref }}
           release_name: Release ${{ env.RELEASE_VERSION }}
           artifacts: console-${{ env.RELEASE_VERSION }}.tgz
           body: |
             Gilligan is available as a tar ball:
              - console-${{ env.RELEASE_VERSION }}.tgz

             Issues fixed in this release
             - https://github.com/skupperproject/gilligan/issues?q=is:issue%20milestone:${{ env.RELEASE_VERSION }}
           draft: true
